apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
      app: myapp
    namespace: new
spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      ports:
        - containerPort: 80